amazon:
  aws:
    account: 377704527648
    access-key: localstack
    secret-key: localstack
    dynamodb:
      endpoint: http://localstack:4566
      region: us-east-1

api-artist:
  artist: "http://localhost:8091"

spring:
  profiles:
    active: dev

logging:
  level:
    root: INFO

